lang: en
timezone: Asia/Dubai
title: Hassan Aloshari
tagline: Cloud Engineer | Aspiring Cloud Security Architect
description: Personal portfolio of Hassan Aloshari
url: "https://hasko0.github.io"
baseurl: ""

github:
  username: hasko0

linkedin:
  username: hassan-aloshari

social:
  name: Hassan Aloshari
  email: haloshari@yahoo.com
  links:
    - https://github.com/hasko0
    - https://www.linkedin.com/in/hassan-aloshari/

avatar: /assets/img/avatar.jpg
theme_mode: dark
