lang: en
timezone: UTC

title: Hassan Aloshari
tagline: Cloud Engineer | Aspiring Cloud Security Architect

url: 'https://aloshari.github.io'

# Social
social:
  name: Hassan Aloshari
  email: haloshari@yahoo.com
  links:
    - https://github.com/hasko0
    - https://www.linkedin.com/in/hassan-aloshari/
    # Add others as needed

# Authors
authors:
  hassan:
    name: Hassan Aloshari
    url: https://aloshari.github.io
