lang: en
timezone: Asia/Dubai

title: Hassan Aloshari
tagline: Cloud Engineer | Aspiring Cloud Security Architect
description: >-
  Personal portfolio and blog of Hassan Aloshari,
  Cloud Engineer and Aspiring Cloud Security Architect.

url: "https://hasko0.github.io"
baseurl: ""

github:
  username: hasko0

linkedin:
  username: hassan-aloshari

social:
  name: Hassan Aloshari
  email: haloshari@yahoo.com
  links:
    - https://github.com/hasko0
    - https://www.linkedin.com/in/hassan-aloshari/

theme: jekyll-theme-chirpy

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true

paginate: 10
